# Generated by Django 5.2.17 on 2026-09-19 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_phone_number', models.CharField(help_text="Kuryer bog'lanishi uchun mo'ljallangan telefon raqami.", max_length=20, verbose_name='Muloqot uchun tel. raqam')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Buyurtmaning barcha mahsulotlari va xizmatlarining umumiy narxi.', max_digits=12, verbose_name='Umumiy summa')),
                ('status', models.CharField(choices=[('preparing', 'Tayyorlanmoqda'), ('in_transit', "Yo'lda"), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='preparing', help_text='Buyurtmaning hozirgi bosqichi.', max_length=20, verbose_name='Holati')),
                ('delivery_address', models.TextField(help_text='Foydalanuvchi tomonidan kiritilgan matnli manzil.', verbose_name='Yetkazib berish manzili')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Xaritadagi GPS kenglik koordinatasi.', max_digits=9, null=True, verbose_name='Kenglik (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Xaritadagi GPS uzoqlik koordinatasi.', max_digits=9, null=True, verbose_name='Uzoqlik (Longitude)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('customer', models.ForeignKey(help_text='Buyurtmani amalga oshirgan foydalanuvchi akkounti.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtmachi (Akkount)')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Buyurtma berilgan vaqtdagi bir birlik mahsulot narxi.', max_digits=10, verbose_name='Sotib olingan paytdagi narxi')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Xarid qilingan mahsulotlar miqdori.', verbose_name='Soni')),
                ('order', models.ForeignKey(help_text="Mahsulot tegishli bo'lgan asosiy buyurtma.", on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(help_text='Sotib olinayotgan katalogdagi mahsulot.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
