# Generated by Django 5.2.17 on 2026-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Tayyorlanmoqda'), ('in_transit', "Yo'lda"), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='preparing', help_text='Buyurtmaning hozirgi bosqichi.', max_length=20, verbose_name='Holati'),
        ),
    ]
