# Generated by Django 5.0.3 on 2026-10-04 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Yetkazib berish'), ('TAKEAWAY', 'Olib ketish')], db_index=True, default='DELIVERY', max_length=10, verbose_name='Buyurtma turi')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha aloqa raqami")),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mo'ljal / Yetkazib berish manzili")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (Longitude)')),
                ('delivery_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hisoblangan masofa (km)')),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', "Karta (Click / Payme o'tkazma)")], default='CASH', max_length=10, verbose_name="To'lov turi")),
                ('payment_status', models.CharField(choices=[('PENDING', "To'lov kutilmoqda"), ('PAID', "To'landi")], db_index=True, default='PENDING', max_length=10, verbose_name="To'lov holati")),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('PREPARING', 'Tayyorlanmoqda'), ('ON_THE_WAY', "Yo'lda"), ('DELIVERED', 'Yetkazib berildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='NEW', max_length=15, verbose_name='Buyurtma holati')),
                ('items_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Taomlar summasi')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Yetkazib berish narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami umumiy summa')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Mijoz izohi')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Bekor qilinish sababi')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqti')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazib berilgan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('product_name', models.CharField(max_length=255, verbose_name='Taom nomi (xarid vaqtidagi)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (xarid vaqtidagi)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma taomi',
                'verbose_name_plural': 'Buyurtma taomlari',
            },
        ),
        migrations.CreateModel(
            name='OrderItemExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('extra_name', models.CharField(max_length=100, verbose_name="Qo'shimcha nomi (xarid vaqtidagi)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Qo'shimcha narxi (xarid vaqtidagi)")),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productextra', verbose_name="Qo'shimcha")),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='orders.orderitem', verbose_name='Buyurtma taomi')),
            ],
            options={
                'verbose_name': "Buyurtma taomi qo'shimchasi",
                'verbose_name_plural': "Buyurtma taomi qo'shimchalari",
            },
        ),
    ]
