# Generated by Django 5.2.17 on 2026-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish')], db_index=True, default='delivery', help_text="Buyurtmani yetkazib berish yoki mijoz o'zi olib ketishi.", max_length=20, verbose_name='Yetkazib berish turi'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Click yoki Karta')], db_index=True, default='cash', help_text="To'lov shakli: Naqd pul yoki Karta/Click (terminal yoki o'tkazma).", max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text="Foydalanuvchi kiritgan manzil (Olib ketishda bo'sh bo'lishi mumkin).", null=True, verbose_name='Yetkazib berish manzili'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_phone_number',
            field=models.CharField(help_text="Kuryer yoki restoran bog'lanishi uchun mo'ljallangan telefon raqami.", max_length=20, verbose_name='Muloqot uchun tel. raqam'),
        ),
    ]
