# Generated by Django 5.0.3 on 2026-10-04 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Kategoriya nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kategoriya rasmi')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Kategoriyalarning menyuda chiqish ketma-ketligi (kichik raqamlar yuqorida chiqadi).', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Belgi olib tashlansa, ushbu kategoriya va uning ichidagi barcha mahsulotlar menyudan butunlay yo'qoladi.", verbose_name="Aktiv (Menyuda ko'rinishi)")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi (Description)')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Tarkibi (Ingredients)')),
                ('weight_or_volume', models.CharField(blank=True, help_text='Masalan: 350g, 0.5L, 32sm', max_length=50, null=True, verbose_name='Vazni yoki Hajmi')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Mahsulot rasmi')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Mahsulotning o'z kategoriyasi ichida chiqish ketma-ketligi (Top taomlarni birinchiga chiqarish uchun).", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Mavsumiy yoki umuman menyudan olib tashlanadigan taomlar uchun o'chiring.", verbose_name="Menyuda ko'rinadimi? (is_active)")),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text="Mahsulot vaqtinchalik tugagan bo'lsa o'chiring (Menyuda 'Sotuvda yo'q' yozuvi bilan kulrang bo'lib turadi).", verbose_name='Sotuvda bormi? (is_available)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name="Qo'shimcha nomi")),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Qo'shimcha narxi (+ summa)")),
                ('is_active', models.BooleanField(default=True, help_text="Ushbu qo'shimchani ro'yxatdan butunlay yashirish uchun o'chiring.", verbose_name='Aktiv (Menyuda bormi?)')),
                ('is_available', models.BooleanField(default=True, help_text="Qo'shimcha (masalan pishloq) vaqtinchalik tugagan bo'lsa o'chiring.", verbose_name='Sotuvda bormi?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='catalog.product', verbose_name='Asosiy mahsulot')),
            ],
            options={
                'verbose_name': "Mahsulot qo'shimchasi",
                'verbose_name_plural': "Mahsulot qo'shimchalari",
                'ordering': ['price', 'name'],
            },
        ),
    ]
